travis:
  secure:
    BINSTAR_TOKEN: 2NGpdONFYvUN/rCP9M1YAIFQpPoo9BgKyXBeQ/146aMulxmKhgcwUbBkREmFuvcEd+gMHz7RTsBu1w9Bvbum03gfMdKB7blxjk9RpB8vxUulvsEm/VIOZuFyAnBT4LvZeVIdABqVkvlwUT7IBSNC08ZIwuWIJPVnHVDSVyvJmgjzgjN1+BjJ+QK+FQxCyKF+FZQ2Oe59PJDTrAomhByq7nbbmBUq5LdbbqBUsc4GCwIw33NTFLBYpzRt87LVnHGk5t8JsAJwV7ceIjdKgbNanzsmIba1Zb3NbD+JHb+BTX4LCjgM0JPv03PHkkHuIGuQ7Qp2WYvK3xsN0xgJjDO3Xg57G5waCa69Isd6oa37WSY5Ed+1Pvp20hp7KYz1wXlvnXM27d/zA+rV7ZxQXs/WB7tjQf0SJrQ5QdodfMt57rO5KSLqWJ+KQZQsBHiGXTR2aKQ9+QuFwRfbl8Eiz76H2ll7vxUfVpM5YKVBC0AfJTahDFQlhn12q0TEglnGu1Q7Aglj3O8eV/DUP3q9PMhcZPefVrfzv9xdXaIO4a/NMABrCCt92kJ8o+0JbyEE8mgl+BccQ9aHJ9Eh/1b8mSQCnuC12lzCMyo9+mwBnUvASvRLxm8cpOiDQAwVODSB7AE12lUqJSjochlPSrL9+f09oOPJC303kV5AOOEqNEMMo7Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
